name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you on reaching out.Your issue will be reviewed shortly.'
        pr-message: 'Welcome to icon-generator. A Jay Khare production'
